/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.11).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package org.irods.rest.api;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2019-09-18T14:35:03.245Z[GMT]")
@Api(value = "token", description = "the token API")
public interface TokenApi {

	@ApiOperation(value = "obtain an encoded jwt for access", nickname = "obtainToken", notes = "Obtain a JWT token for accessing REST endpoints ", tags = {
			"auth", })
	@ApiResponses(value = { @ApiResponse(code = 200, message = "Successfully authenticated"),
			@ApiResponse(code = 401, message = "Authorization failed") })
	@RequestMapping(value = "/token", method = RequestMethod.POST)
	ResponseEntity<String> obtainToken();

}
